<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "Modifications".
 *
 * @property integer $id
 * @property integer $label
 */
class Modifications extends \yii\db\ActiveRecord
{
    public $linked_projects;

  /**
   * @inheritdoc
   */
  public static function tableName()
  {
    return 'modifications';
  }

  public function afterFind()
  {
      parent::afterFind(); // TODO: Change the autogenerated stub

      $this->linked_projects = ProjectLinks::getLinksByMod($this->id);
  }

    /**
   * @inheritdoc
   */
  public function rules()
  {
    return [
      [['label',], 'safe']
    ];
  }

  /**
   * @inheritdoc
   */
  public function attributeLabels()
  {
    return [
      'id' => 'ID',
      'label' => 'Пометка',
    ];
  }
}
